export const STATION_REPOSITORY: string = 'STATION_REPOSITORY';
export const ROUTE_REPOSITORY: string = 'ROUTE_REPOSITORY';
export const ROUTES_STATION_REPOSITORY: string = 'ROUTES_STATION_REPOSITORY';
export const ROUTES_TRIP_REPOSITORY: string = 'ROUTES_TRIP_REPOSITORY';
export const STATIONS_CONNECTION_REPOSITORY: string = 'STATIONS_CONNECTION_REPOSITORY';
export const ZONE_REPOSITORY: string = 'ZONE_REPOSITORY';